const ing = (name, amount, unit, category = 'otros') => ({ name, amount, unit, category });
const n = (kcal, protein, carbs, fat, fiber) => ({ kcal, protein, carbs, fat, fiber });
const recipe = (id, name, emoji, mealTypes, totalTime, servings, nutrition, estimatedCost, ingredients, options = {}) => ({
  id, name, emoji, mealTypes, totalTime, prepTime: Math.max(5, totalTime - (options.cookTime || 10)), cookTime: options.cookTime || 10,
  servings, nutrition, estimatedCost, ingredients, description: options.description || 'Una receta sencilla, equilibrada y pensada para el día a día.',
  steps: options.steps || [],
  traits: options.traits || [], allergens: options.allergens || [], equipment: options.equipment || [], tags: options.tags || [],
  rating: options.rating || 4.6, ratingCount: options.ratingCount || 0, ratingType: options.ratingType || 'system_estimate', source: 'Datos de demostración NutriHome'
});

export const DEMO_RECIPES = [
  recipe('rec-avena-pera', 'Avena cremosa con pera', '🥣', ['breakfast'], 10, 1, n(420, 22, 55, 12, 9), 1.55, [ing('avena', 60, 'g', 'cereales'), ing('leche de soja', 220, 'ml', 'bebidas'), ing('pera', 1, 'unidad', 'frutas'), ing('semillas de chía', 10, 'g', 'semillas')], { traits: ['soy'], allergens: ['soja'], tags: ['rápida', 'vegana', 'fibra', 'sin huevo'], description: 'Avena cálida con pera, canela y chía; saciante sin resultar pesada.', cookTime: 5, steps: ['Lava la pera, retira el corazón y córtala en dados pequeños; reserva unas láminas para terminar.', 'Pon la avena, la leche de soja y tres cuartas partes de la pera en un cazo. Cocina a fuego medio 4–5 minutos, removiendo, hasta que la avena quede cremosa.', 'Retira del fuego, incorpora la chía y deja reposar 2 minutos para que espese.', 'Sirve con la pera reservada y, si te apetece, una pizca de canela.'] }),
  recipe('rec-tostada-hummus', 'Tostadas de hummus y tomate', '🍅', ['breakfast'], 8, 1, n(390, 18, 52, 13, 10), 1.7, [ing('pan integral', 80, 'g', 'cereales'), ing('hummus', 70, 'g', 'refrigerados'), ing('tomate', 120, 'g', 'verduras')], { traits: ['gluten', 'sesame'], allergens: ['gluten', 'sésamo'], tags: ['muy rápida', 'vegana', 'económica', 'sin huevo'], cookTime: 3, steps: ['Tuesta el pan integral 2–3 minutos, hasta que los bordes estén dorados y el centro siga tierno.', 'Lava el tomate, sécalo y córtalo en rodajas finas.', 'Reparte el hummus sobre las tostadas y coloca encima las rodajas de tomate.', 'Termina con pimienta negra y unas gotas de aceite de oliva, si tienes, y sirve enseguida.'] }),
  recipe('rec-yogur-granola', 'Yogur con granola y frutos rojos', '🫐', ['breakfast', 'snack'], 5, 1, n(355, 23, 41, 11, 6), 1.95, [ing('yogur natural', 200, 'g', 'refrigerados'), ing('granola', 35, 'g', 'cereales'), ing('arándanos', 80, 'g', 'frutas')], { traits: ['dairy', 'gluten'], allergens: ['lácteos', 'gluten'], tags: ['muy rápida', 'vegetariana', 'alta proteína', 'sin huevo'], cookTime: 0, steps: ['Lava los arándanos con suavidad y sécalos bien para no aguar el yogur.', 'Remueve el yogur hasta que quede cremoso y pásalo a un bol o vaso.', 'Añade la granola justo antes de comer para conservar su textura crujiente.', 'Corona con los arándanos y sirve frío.'] }),
  recipe('rec-revuelto-tofu', 'Revuelto de tofu y espinacas', '🍳', ['breakfast', 'dinner'], 15, 2, n(330, 28, 18, 17, 7), 3.4, [ing('tofu firme', 300, 'g', 'refrigerados'), ing('espinacas frescas', 160, 'g', 'verduras'), ing('tomate', 160, 'g', 'verduras'), ing('pan integral', 80, 'g', 'cereales')], { traits: ['soy', 'gluten'], allergens: ['soja', 'gluten'], tags: ['rápida', 'vegana', 'alta proteína', 'sin huevo'], cookTime: 8, steps: ['Escurre el tofu y desmenúzalo con las manos hasta obtener trozos parecidos a un revuelto. Corta el tomate en dados.', 'Calienta una sartén con un poco de aceite y saltea el tofu 4 minutos con sal, pimienta y una pizca de cúrcuma si tienes.', 'Añade el tomate y las espinacas; cocina 3–4 minutos, hasta que el tomate se ablande y las hojas pierdan volumen.', 'Tuesta el pan y sirve el revuelto caliente encima o al lado.'] }),
  recipe('rec-tortilla-espinaca', 'Tortilla de espinacas y patata', '🥔', ['breakfast', 'dinner'], 25, 2, n(405, 25, 38, 17, 6), 3.1, [ing('huevos', 4, 'unidad', 'refrigerados'), ing('patatas', 320, 'g', 'verduras'), ing('espinacas', 120, 'g', 'verduras'), ing('cebolla', 80, 'g', 'verduras')], { traits: ['egg'], allergens: ['huevo'], tags: ['vegetariana', 'económica'], cookTime: 17, steps: ['Pela las patatas y córtalas en dados de 1 cm; pica la cebolla y lava las espinacas.', 'Cocina la patata y la cebolla en una sartén antiadherente con un poco de aceite y una cucharada de agua, tapadas, 10–12 minutos; remueve hasta que estén tiernas.', 'Añade las espinacas y cocina 2 minutos. Bate los huevos con sal, incorpora las verduras y mezcla.', 'Vierte la mezcla en la sartén y cuaja 3–4 minutos por un lado. Dale la vuelta con un plato y cocina 2–3 minutos más, hasta que el huevo esté completamente cuajado.'] }),
  recipe('rec-chia-cacao', 'Pudin de chía y cacao', '🍫', ['breakfast', 'snack'], 10, 2, n(345, 16, 35, 17, 12), 2.8, [ing('semillas de chía', 55, 'g', 'semillas'), ing('leche vegetal', 400, 'ml', 'bebidas'), ing('cacao puro', 12, 'g', 'otros'), ing('plátano', 1, 'unidad', 'frutas')], { tags: ['vegana', 'sin huevo', 'meal prep'], cookTime: 0, description: 'Se prepara en diez minutos y reposa en frío; perfecto para adelantar desayunos.', steps: ['Machaca medio plátano en un bol hasta obtener un puré sin grumos; corta la otra mitad en rodajas y resérvala.', 'Añade la leche vegetal y el cacao al puré y bate hasta que el cacao se disuelva.', 'Incorpora la chía, remueve bien y vuelve a mezclar a los 5 minutos para evitar grumos.', 'Reparte en dos recipientes, tapa y refrigera al menos 4 horas —mejor toda la noche—. Sirve con las rodajas de plátano.'] }),

  recipe('rec-bowl-garbanzos', 'Bowl mediterráneo de garbanzos', '🥙', ['lunch', 'dinner'], 20, 2, n(548, 27, 68, 18, 15), 4.2, [ing('garbanzos cocidos', 320, 'g', 'legumbres'), ing('arroz integral', 140, 'g', 'cereales'), ing('tomate', 200, 'g', 'verduras'), ing('pepino', 160, 'g', 'verduras'), ing('limón', 1, 'unidad', 'frutas')], { tags: ['vegana', 'sin huevo', 'económica', 'fibra'], cookTime: 12, description: 'Un bol fresco y completo que aprovecha legumbres cocidas y verduras de temporada.', steps: ['Cuece el arroz integral en agua con sal según el tiempo del envase; escúrrelo y déjalo templar.', 'Enjuaga y escurre los garbanzos. Corta el tomate y el pepino en dados de tamaño parecido.', 'Bate el zumo de limón con un poco de aceite, sal y pimienta para hacer el aliño.', 'Reparte el arroz, los garbanzos y las verduras en dos boles; vierte el aliño por encima y mezcla al comer.'] }),
  recipe('rec-lentejas-arroz', 'Lentejas especiadas con arroz', '🍛', ['lunch'], 30, 3, n(585, 29, 89, 12, 18), 4.5, [ing('lentejas cocidas', 480, 'g', 'legumbres'), ing('arroz', 210, 'g', 'cereales'), ing('tomate triturado', 300, 'g', 'conservas'), ing('cebolla', 120, 'g', 'verduras'), ing('zanahoria', 180, 'g', 'verduras')], { tags: ['vegana', 'económica', 'batch cooking', 'sin huevo'], cookTime: 22, steps: ['Cuece el arroz en agua con sal según el envase mientras preparas las lentejas.', 'Pica la cebolla y corta la zanahoria en dados pequeños. Sofríelas con un poco de aceite 7–8 minutos, hasta que se ablanden.', 'Añade comino, pimentón o curry al gusto y remueve 30 segundos. Incorpora el tomate triturado y cocina 5 minutos.', 'Enjuaga las lentejas, agrégalas con un chorrito de agua y cocina 8 minutos a fuego suave. Sirve sobre el arroz cocido.'] }),
  recipe('rec-pasta-atun', 'Pasta integral con atún y tomate', '🍝', ['lunch'], 22, 2, n(610, 43, 77, 15, 10), 4.8, [ing('pasta integral', 180, 'g', 'cereales'), ing('atún en conserva', 2, 'lata', 'conservas'), ing('tomate triturado', 240, 'g', 'conservas'), ing('espinacas', 100, 'g', 'verduras')], { traits: ['fish', 'gluten'], allergens: ['pescado', 'gluten'], tags: ['pescetariana', 'alta proteína', 'rápida'], cookTime: 14, steps: ['Cuece la pasta en abundante agua con sal hasta que quede al dente. Reserva medio vaso del agua de cocción y escurre.', 'Calienta el tomate triturado en una sartén amplia 5–6 minutos con pimienta y orégano, si tienes.', 'Añade las espinacas y cocina 2 minutos, hasta que se ablanden. Incorpora el atún bien escurrido y calienta 1 minuto sin deshacerlo demasiado.', 'Mezcla la pasta con la salsa; añade un poco del agua reservada si hace falta para que quede jugosa y sirve.'] }),
  recipe('rec-pollo-quinoa', 'Pollo al limón con quinoa', '🍋', ['lunch', 'dinner'], 28, 2, n(570, 51, 55, 16, 8), 6.9, [ing('pechuga de pollo', 320, 'g', 'carnes'), ing('quinoa', 150, 'g', 'cereales'), ing('calabacín', 220, 'g', 'verduras'), ing('limón', 1, 'unidad', 'frutas')], { traits: ['meat'], tags: ['alta proteína', 'sin huevo'], cookTime: 20, steps: ['Enjuaga la quinoa en un colador fino. Cuécela con el doble de su volumen de agua y una pizca de sal durante 12–15 minutos; apaga y deja reposar tapada.', 'Corta el calabacín en medias lunas y la pechuga en tiras. Sazona el pollo con sal, pimienta y la mitad del zumo de limón.', 'Dora el pollo en una sartén con un poco de aceite 5–7 minutos, moviéndolo, hasta que no quede rosado en el centro; retíralo a un plato.', 'Saltea el calabacín 4–5 minutos. Devuelve el pollo, añade el resto del limón y sirve todo con la quinoa.'] }),
  recipe('rec-curry-tofu', 'Curry rápido de tofu y coco', '🥥', ['lunch', 'dinner'], 25, 3, n(520, 30, 52, 23, 10), 6.3, [ing('tofu firme', 420, 'g', 'refrigerados'), ing('leche de coco', 300, 'ml', 'conservas'), ing('arroz', 180, 'g', 'cereales'), ing('espinacas', 180, 'g', 'verduras')], { traits: ['soy'], allergens: ['soja'], tags: ['vegana', 'alta proteína', 'sin huevo'], cookTime: 17, steps: ['Cuece el arroz en agua con sal según el tiempo indicado en el envase.', 'Escurre el tofu, sécalo y córtalo en dados. Dóralo en una sartén amplia con un poco de aceite durante 6–7 minutos, girándolo.', 'Añade una cucharada de curry en polvo, remueve unos segundos y vierte la leche de coco. Cocina a fuego medio 5 minutos.', 'Incorpora las espinacas y cocina 2–3 minutos más, hasta que se ablanden. Prueba de sal y sirve el curry con el arroz.'] }),
  recipe('rec-pasta-alubias', 'Pasta cremosa de alubias blancas', '🫘', ['lunch'], 25, 3, n(560, 31, 82, 13, 17), 4.9, [ing('pasta integral', 240, 'g', 'cereales'), ing('alubias blancas', 360, 'g', 'legumbres'), ing('tomate', 250, 'g', 'verduras'), ing('ajo', 2, 'unidad', 'verduras')], { traits: ['gluten'], allergens: ['gluten'], tags: ['vegana', 'alta proteína', 'económica', 'sin huevo'], cookTime: 15, steps: ['Cuece la pasta integral en agua con sal hasta que esté al dente; reserva 150 ml del agua y escurre.', 'Pica el ajo y corta el tomate en dados. Sofríe el ajo 30 segundos, añade el tomate y cocina 5–6 minutos.', 'Enjuaga las alubias. Tritura la mitad con el agua de cocción reservada hasta lograr una crema suave.', 'Añade a la sartén la crema y las alubias enteras, incorpora la pasta y cocina 2 minutos removiendo hasta que la salsa la cubra.'] }),

  recipe('rec-yogur-nueces', 'Yogur, nueces y arándanos', '🫐', ['snack'], 5, 1, n(275, 18, 25, 11, 4), 1.65, [ing('yogur natural', 170, 'g', 'refrigerados'), ing('nueces', 15, 'g', 'frutos secos'), ing('arándanos', 70, 'g', 'frutas')], { traits: ['dairy', 'nuts'], allergens: ['lácteos', 'frutos secos'], tags: ['muy rápida', 'vegetariana', 'sin huevo'], cookTime: 0, steps: ['Lava los arándanos, escúrrelos y sécalos con cuidado.', 'Trocea las nueces de forma gruesa para que mantengan textura.', 'Pon el yogur en un bol y añade los arándanos.', 'Reparte las nueces por encima justo antes de servir.'] }),
  recipe('rec-hummus-zanahoria', 'Hummus con bastones de zanahoria', '🥕', ['snack'], 7, 1, n(250, 11, 30, 10, 9), 1.25, [ing('hummus', 90, 'g', 'refrigerados'), ing('zanahoria', 180, 'g', 'verduras')], { traits: ['sesame'], allergens: ['sésamo'], tags: ['muy rápida', 'vegana', 'económica', 'sin huevo'], cookTime: 0, steps: ['Lava y pela la zanahoria.', 'Córtala primero en tramos y después en bastones de grosor uniforme, fáciles de mojar.', 'Remueve el hummus y pásalo a un cuenco pequeño; añade pimentón o unas gotas de aceite si te apetece.', 'Sirve el hummus frío acompañado de los bastones de zanahoria.'] }),
  recipe('rec-batido-soja', 'Batido de soja, plátano y avena', '🥤', ['breakfast', 'snack'], 5, 1, n(365, 24, 54, 8, 7), 1.4, [ing('leche de soja', 300, 'ml', 'bebidas'), ing('plátano', 1, 'unidad', 'frutas'), ing('avena', 35, 'g', 'cereales')], { traits: ['soy'], allergens: ['soja'], equipment: ['blender'], tags: ['muy rápida', 'vegana', 'alta proteína', 'sin huevo'], cookTime: 0, steps: ['Pela el plátano, córtalo en trozos y ponlo en el vaso de la batidora.', 'Añade la leche de soja y la avena.', 'Tritura 45–60 segundos, hasta que la avena quede fina y el batido sea homogéneo.', 'Déjalo reposar 1 minuto; si queda demasiado espeso, añade un poco más de leche de soja y vuelve a batir.'] }),
  recipe('rec-manzana-cacahuete', 'Manzana con crema de cacahuete', '🍎', ['snack'], 3, 1, n(265, 8, 31, 14, 7), 1.0, [ing('manzana', 1, 'unidad', 'frutas'), ing('crema de cacahuete', 28, 'g', 'frutos secos')], { traits: ['nuts'], allergens: ['cacahuete'], tags: ['muy rápida', 'vegana', 'económica', 'sin huevo'], cookTime: 0, steps: ['Lava y seca bien la manzana.', 'Córtala en gajos y retira el corazón y las semillas.', 'Remueve la crema de cacahuete para integrar el aceite natural y sírvela en un cuenco.', 'Unta cada gajo al comer para que la manzana conserve su textura crujiente.'] }),
  recipe('rec-tostada-queso', 'Tostada de queso fresco y uvas', '🍇', ['snack'], 6, 1, n(290, 17, 39, 8, 5), 1.75, [ing('pan integral', 60, 'g', 'cereales'), ing('queso fresco', 70, 'g', 'refrigerados'), ing('uvas', 90, 'g', 'frutas')], { traits: ['dairy', 'gluten'], allergens: ['lácteos', 'gluten'], tags: ['muy rápida', 'vegetariana', 'sin huevo'], cookTime: 2, steps: ['Tuesta el pan integral 2 minutos, hasta que quede ligeramente dorado.', 'Escurre el queso fresco, sécalo con papel de cocina y córtalo en láminas.', 'Lava las uvas y córtalas por la mitad; retira las semillas si las tienen.', 'Coloca el queso sobre la tostada, reparte las uvas y termina con pimienta negra si te gusta el contraste.'] }),
  recipe('rec-bolas-avena', 'Bolas de avena y dátil', '🌰', ['snack'], 15, 6, n(210, 7, 29, 9, 5), 2.7, [ing('avena', 120, 'g', 'cereales'), ing('dátiles', 150, 'g', 'frutas'), ing('almendras', 60, 'g', 'frutos secos')], { traits: ['nuts'], allergens: ['frutos secos'], equipment: ['blender'], tags: ['vegana', 'meal prep', 'sin huevo'], cookTime: 0, steps: ['Retira los huesos de los dátiles. Si están secos, cúbrelos con agua caliente 5 minutos y escúrrelos bien.', 'Tritura las almendras y la avena hasta obtener una miga gruesa, sin convertirlas por completo en harina.', 'Añade los dátiles y tritura por pulsos hasta que la mezcla se compacte al presionarla; incorpora una cucharadita de agua solo si sigue suelta.', 'Forma 12 bolas con las manos y refrigéralas 30 minutos. Guárdalas tapadas en la nevera.'] }),

  recipe('rec-tofu-verduras', 'Tofu crujiente con verduras', '🥦', ['dinner'], 25, 2, n(603, 42, 61, 21, 13), 5.2, [ing('tofu firme', 360, 'g', 'refrigerados'), ing('brócoli', 300, 'g', 'verduras'), ing('pimiento rojo', 180, 'g', 'verduras'), ing('arroz', 130, 'g', 'cereales'), ing('salsa de soja', 25, 'ml', 'condimentos')], { traits: ['soy'], allergens: ['soja'], tags: ['vegana', 'alta proteína', 'sin huevo'], cookTime: 17, steps: ['Cuece el arroz en agua con sal según el envase. Separa el brócoli en ramilletes y corta el pimiento en tiras.', 'Escurre y seca muy bien el tofu; córtalo en dados y dóralo en una sartén amplia con aceite durante 7–8 minutos, girándolo hasta que varias caras estén crujientes.', 'Retira el tofu. Saltea el brócoli y el pimiento 5–6 minutos; añade dos cucharadas de agua y tapa 2 minutos para que el brócoli quede tierno pero firme.', 'Devuelve el tofu a la sartén, añade la salsa de soja y saltea 1 minuto. Sirve sobre el arroz.'] }),
  recipe('rec-salmon-boniato', 'Salmón con boniato y judías verdes', '🐟', ['dinner'], 30, 2, n(580, 44, 48, 24, 9), 9.4, [ing('salmón', 300, 'g', 'pescados'), ing('boniato', 400, 'g', 'verduras'), ing('judías verdes', 260, 'g', 'verduras')], { traits: ['fish'], allergens: ['pescado'], equipment: ['oven'], tags: ['pescetariana', 'alta proteína', 'sin huevo'], cookTime: 22, steps: ['Calienta el horno a 210 °C. Pela el boniato, córtalo en dados de 2 cm y mézclalo en una bandeja con aceite, sal y pimienta.', 'Hornea el boniato 12 minutos. Mientras, retira las puntas de las judías verdes y sécalas; sazona el salmón.', 'Añade las judías a la bandeja, remueve y coloca el salmón con la piel hacia abajo. Hornea todo 10–12 minutos más.', 'Comprueba que el salmón se separa en lascas y está opaco en el centro; sirve inmediatamente con el boniato y las judías.'] }),
  recipe('rec-crema-calabacin', 'Crema de calabacín con alubias', '🥒', ['dinner'], 25, 3, n(395, 21, 52, 11, 15), 3.8, [ing('calabacín', 700, 'g', 'verduras'), ing('alubias blancas', 300, 'g', 'legumbres'), ing('cebolla', 120, 'g', 'verduras'), ing('caldo vegetal', 600, 'ml', 'conservas')], { equipment: ['blender'], tags: ['vegana', 'económica', 'sin huevo', 'batch cooking'], cookTime: 18, steps: ['Pica la cebolla y corta el calabacín en medias lunas; no hace falta pelarlo si la piel está tierna.', 'Sofríe la cebolla con un poco de aceite 4–5 minutos. Añade el calabacín y cocina 3 minutos más.', 'Enjuaga las alubias. Incorpora dos tercios de ellas y el caldo; hierve suavemente 10 minutos, hasta que el calabacín esté tierno.', 'Tritura hasta obtener una crema lisa, ajusta de sal y añade las alubias reservadas. Calienta 2 minutos antes de servir.'] }),
  recipe('rec-tortilla-patata', 'Tortilla de patata ligera', '🍳', ['dinner'], 35, 3, n(455, 26, 42, 20, 5), 4.0, [ing('huevos', 6, 'unidad', 'refrigerados'), ing('patatas', 600, 'g', 'verduras'), ing('cebolla', 140, 'g', 'verduras')], { traits: ['egg'], allergens: ['huevo'], tags: ['vegetariana', 'económica'], cookTime: 27, steps: ['Pela las patatas, córtalas en láminas finas y pica la cebolla.', 'Pon ambas en una sartén antiadherente con dos cucharadas de aceite y cuatro de agua. Sala, tapa y cocina a fuego medio-bajo 18–20 minutos, removiendo, hasta que estén tiernas.', 'Bate los huevos en un bol grande, añade la patata y la cebolla escurridas y deja reposar la mezcla 2 minutos.', 'Vierte en la sartén y cuaja 4 minutos. Da la vuelta con un plato y cocina 3–4 minutos por la otra cara, hasta que el centro quede completamente cuajado.'] }),
  recipe('rec-tacos-alubia', 'Tacos de alubias negras y maíz', '🌮', ['lunch', 'dinner'], 20, 3, n(495, 24, 72, 13, 18), 4.6, [ing('tortillas de maíz', 6, 'unidad', 'cereales'), ing('alubias negras', 420, 'g', 'legumbres'), ing('maíz', 180, 'g', 'conservas'), ing('tomate', 180, 'g', 'verduras')], { tags: ['vegana', 'económica', 'rápida', 'sin huevo'], cookTime: 10, steps: ['Enjuaga y escurre las alubias y el maíz. Corta el tomate en dados pequeños.', 'Calienta las alubias y el maíz en una sartén con comino y pimentón al gusto durante 5–6 minutos; aplasta ligeramente algunas alubias para ligar el relleno.', 'Calienta las tortillas, una a una, unos 20 segundos por cada lado en una sartén seca y mantenlas tapadas con un paño.', 'Rellena cada tortilla con la mezcla caliente, reparte el tomate por encima y sirve dos tacos por persona.'] }),
  recipe('rec-wok-tempeh', 'Wok de tempeh, arroz y verduras', '🥢', ['dinner'], 24, 2, n(565, 38, 67, 18, 12), 6.1, [ing('tempeh', 300, 'g', 'refrigerados'), ing('arroz', 140, 'g', 'cereales'), ing('brócoli', 240, 'g', 'verduras'), ing('pimiento', 160, 'g', 'verduras'), ing('salsa de soja', 25, 'ml', 'condimentos')], { traits: ['soy'], allergens: ['soja'], tags: ['vegana', 'alta proteína', 'sin huevo'], cookTime: 16, steps: ['Cuece el arroz en agua con sal según el envase. Separa el brócoli en ramilletes pequeños y corta el pimiento y el tempeh en tiras.', 'Calienta bien un wok o sartén amplia con un poco de aceite y dora el tempeh 4–5 minutos. Retíralo.', 'Saltea el brócoli y el pimiento a fuego vivo 5 minutos; añade dos cucharadas de agua y cocina 2 minutos más para ablandar el brócoli.', 'Devuelve el tempeh, incorpora el arroz cocido y la salsa de soja, y saltea todo 2 minutos hasta que esté bien caliente.'] }),
  recipe('rec-ensalada-quinoa', 'Ensalada tibia de quinoa y edamame', '🥗', ['lunch', 'dinner'], 20, 2, n(505, 29, 65, 17, 14), 5.6, [ing('quinoa', 150, 'g', 'cereales'), ing('edamame', 240, 'g', 'congelados'), ing('espinacas', 140, 'g', 'verduras'), ing('tomate', 180, 'g', 'verduras')], { traits: ['soy'], allergens: ['soja'], tags: ['vegana', 'alta proteína', 'sin huevo'], cookTime: 12, steps: ['Enjuaga la quinoa y cuécela con el doble de su volumen de agua y una pizca de sal durante 12–15 minutos; deja reposar tapada 5 minutos.', 'Cuece el edamame congelado en agua hirviendo según el envase, escúrrelo y, si viene en vaina, extrae los granos.', 'Corta el tomate en dados y coloca las espinacas en un bol grande. Añade la quinoa aún tibia para que las hojas se ablanden ligeramente.', 'Incorpora el edamame y el tomate; aliña con aceite, sal, pimienta y unas gotas de vinagre o limón, y mezcla.'] })
];

const futureDate = days => {
  const date = new Date();
  date.setHours(12, 0, 0, 0);
  date.setDate(date.getDate() + days);
  return date.toISOString().slice(0, 10);
};

export function createDemoPantry() {
  return [
    { id: 'pantry-rice', name: 'arroz', quantity: 520, unit: 'g', minQuantity: 250, category: 'cereales', location: 'pantry', expiry: futureDate(150), price: 1.65 },
    { id: 'pantry-chickpea', name: 'garbanzos cocidos', quantity: 500, unit: 'g', minQuantity: 200, category: 'legumbres', location: 'pantry', expiry: futureDate(80), price: 1.2 },
    { id: 'pantry-tomato', name: 'tomate', quantity: 420, unit: 'g', minQuantity: 200, category: 'verduras', location: 'fridge', expiry: futureDate(2), price: 1.8 },
    { id: 'pantry-spinach', name: 'espinacas frescas', quantity: 180, unit: 'g', minQuantity: 100, category: 'verduras', location: 'fridge', expiry: futureDate(1), price: 1.6 },
    { id: 'pantry-tofu', name: 'tofu firme', quantity: 400, unit: 'g', minQuantity: 200, category: 'refrigerados', location: 'fridge', expiry: futureDate(3), price: 2.4 },
    { id: 'pantry-oats', name: 'avena', quantity: 430, unit: 'g', minQuantity: 150, category: 'cereales', location: 'pantry', expiry: futureDate(120), price: 1.4 },
    { id: 'pantry-soy', name: 'leche de soja', quantity: 750, unit: 'ml', minQuantity: 500, category: 'bebidas', location: 'fridge', expiry: futureDate(5), price: 1.2 },
    { id: 'pantry-onion', name: 'cebolla', quantity: 260, unit: 'g', minQuantity: 300, category: 'verduras', location: 'pantry', expiry: futureDate(12), price: 0.8 },
    { id: 'pantry-blueberry', name: 'arándanos', quantity: 110, unit: 'g', minQuantity: 80, category: 'frutas', location: 'fridge', expiry: futureDate(2), price: 2.2 },
    { id: 'pantry-yogurt', name: 'yogur natural', quantity: 300, unit: 'g', minQuantity: 200, category: 'refrigerados', location: 'fridge', expiry: futureDate(4), price: 1.4 },
    { id: 'pantry-potato', name: 'patatas', quantity: 900, unit: 'g', minQuantity: 500, category: 'verduras', location: 'pantry', expiry: futureDate(18), price: 1.2 },
    { id: 'pantry-carrot', name: 'zanahoria', quantity: 240, unit: 'g', minQuantity: 200, category: 'verduras', location: 'fridge', expiry: futureDate(6), price: 0.7 }
  ];
}

export const DEFAULT_PROFILE = {
  configured: false, diet: 'vegetarian', eatsEgg: false, eatsDairy: true,
  allergies: [], restrictions: [], dislikes: [], calorieTarget: 2050, proteinTarget: 110,
  carbTarget: 245, fatTarget: 68, weeklyBudget: 65, monthlyBudget: 260, people: 2,
  maxCookingTime: 30, supermarket: '', equipment: ['oven', 'microwave', 'blender'], notifications: { expiry: true, lowStock: true, planning: false }
};

export const DEMO_EXERCISE = [
  { id: 'ex-1', day: 1, type: 'Fuerza', duration: 50, intensity: 'high', calories: 320 },
  { id: 'ex-2', day: 3, type: 'Carrera suave', duration: 35, intensity: 'medium', calories: 280 },
  { id: 'ex-3', day: 5, type: 'Movilidad', duration: 25, intensity: 'low', calories: 90 }
];
