import assert from 'node:assert/strict';
import { access, readFile } from 'node:fs/promises';

const html = await readFile(new URL('../index.html', import.meta.url), 'utf8');
const app = await readFile(new URL('../app.js', import.meta.url), 'utf8');
const demoData = await readFile(new URL('../demo-data.js', import.meta.url), 'utf8');
const manifest = JSON.parse(await readFile(new URL('../manifest.webmanifest', import.meta.url), 'utf8'));
const worker = await readFile(new URL('../sw.js', import.meta.url), 'utf8');
const ids = [...html.matchAll(/id="([^"]+)"/g)].map(match => match[1]);
assert.deepEqual(ids.filter((id, index) => ids.indexOf(id) !== index), [], 'No hay IDs HTML duplicados');

for (const view of ['week', 'recipes', 'favorites', 'pantry', 'shopping', 'more']) {
  assert.match(html, new RegExp(`data-view="${view}"`));
  assert.match(html, new RegExp(`data-nav="${view}"`));
}
assert.match(html, /id="onboarding-form"/);
assert.match(html, /id="recipe-form"/);
assert.match(html, /id="pantry-form"/);
assert.match(html, /id="body-metrics-form"/);
assert.match(html, /id="body-goal-form"/);
assert.match(html, /id="weight-log-form"/);
assert.match(html, /id="weight-chart"/);
assert.match(html, /name="age"/);
assert.match(html, /name="muscleKg"/);
assert.match(html, /aria-live="polite"/);
assert.match(html, /class="skip-link"/);
assert.doesNotMatch(`${html}\n${app}\n${demoData}`, />TM<|Tu nombre|profile-name|profile-card-name/i);
assert.match(app, /getHours\(\) < 14 \? 'Buenos días' : 'Buenas tardes'/);
assert.equal(manifest.name.startsWith('NutriHome'), true);
assert.equal(manifest.icons.some(icon => icon.sizes === '192x192'), true);
assert.equal(manifest.icons.some(icon => icon.sizes === '512x512'), true);
for (const asset of ['nutrihome-core.js', 'demo-data.js', 'recipe-library.js', 'recipe-estimator.js', 'storage.js', 'app.js', 'recipe-families.js', 'recipe-specials.js', 'recipe-photos.js', 'recipe-image-list.js']) assert.equal(worker.includes(asset), true);
assert.match(html, /id="recipe-load-more"/);
assert.match(html, /value="lacto_vegetarian"/);
assert.match(html, /value="ovo_vegetarian"/);
assert.match(html, /value="flexitarian"/);
const shellMatch = worker.match(/const APP_SHELL = \[([\s\S]*?)\];/);
assert.ok(shellMatch, 'El service worker declara el app shell');
for (const match of shellMatch[1].matchAll(/'\.\/([^']+)'/g)) await access(new URL(`../${match[1].split('?')[0]}`, import.meta.url));
for (const dialogId of ['onboarding-dialog', 'pantry-dialog', 'recipe-form-dialog', 'generator-dialog', 'swipe-dialog', 'simple-dialog']) assert.match(html, new RegExp(`data-close-dialog="${dialogId}"`));
assert.match(html, /id="recipe-estimate-preview"/);
assert.match(html, /name="coverImage"/);
assert.match(html, /name="weeks"/);
assert.match(html, /name="source"/);
assert.match(html, /name="scope"/);
assert.match(html, /id="planning-reminder-hour"/);
assert.match(html, /id="download-calendar-reminder"/);
assert.match(html, /v1\.9\.1/);
assert.match(app, /rankMealCandidates/);
assert.doesNotMatch(app, /fitFallbackCover|coverPosition|commons\.wikimedia/);
assert.match(app, /recipe-photos/);
assert.match(app, /generationRecipePool/);
assert.match(app, /generationDays/);
assert.match(app, /data-exclude-ingredient/);
assert.match(app, /<details class="variant-suggestions"><summary>Ideas para cambiar ingredientes/);
assert.match(app, /No se cuentan como platos distintos/);
const catalogRenderer = app.split('function renderRecipes() {')[1]?.split('function renderFavorites() {')[0] || '';
assert.doesNotMatch(catalogRenderer.match(/\.sort\(\(a, b\) =>[^;]+;/)?.[0] || '', /favorites/, 'Guardar una receta no la adelanta en el catálogo general');
assert.doesNotMatch(app, /ingredientSymbol/);
assert.doesNotMatch(app, /seleccionada y guardada en favoritos/);
const swipeHandler = app.match(/function handleSwipe\(choice\) \{[\s\S]*?\n\}/)?.[0] || '';
assert.doesNotMatch(swipeHandler, /favorites/, 'Elegir en el selector no debe alterar favoritos');

console.log('NutriHome UI/PWA smoke tests passed');
